language: python
matrix:
  include:
    - python: 3.8
install: 
  - pip install numpy
  - pip install certifi
  - sudo apt-get install libssl-dev libcurl4-openssl-dev libyaml-dev build-essential libopenblas-dev libcap-dev ffmpeg
  - pip install -e .
before_script:
  - pip install coveralls
  - pip install pytest-cover
script: 
  - py.test tods/tests/ --cov=tods
after_success:
  - coveralls
